-- MySQL Script generated by MySQL Workbench
-- 08/19/16 11:14:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema zndfilm
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `zndfilm` ;

-- -----------------------------------------------------
-- Schema zndfilm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zndfilm` DEFAULT CHARACTER SET utf8 ;
USE `zndfilm` ;

-- -----------------------------------------------------
-- Table `zndfilm`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zndfilm`.`users` ;

CREATE TABLE IF NOT EXISTS `zndfilm`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `social_no` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `privilege` INT NULL,
  `picture` VARCHAR(256) NULL,
  `active` TINYINT(1) NULL DEFAULT 0,
  `editable` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '		';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
